// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_training/test/unit_test/data/use_case/fetch_weather_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_training/data/models/app_api_result.dart' as _i2;
import 'package:flutter_training/data/models/weather/weather.dart' as _i4;
import 'package:flutter_training/data/models/weather/weather_request.dart'
    as _i5;
import 'package:flutter_training/data/repository/weather_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppApiResult_0<T> extends _i1.SmartFake
    implements _i2.AppApiResult<T> {
  _FakeAppApiResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i3.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppApiResult<_i4.Weather> getWeather(
          {required _i5.WeatherRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [],
          {#request: request},
        ),
        returnValue: _FakeAppApiResult_0<_i4.Weather>(
          this,
          Invocation.method(
            #getWeather,
            [],
            {#request: request},
          ),
        ),
      ) as _i2.AppApiResult<_i4.Weather>);
}
